### ISSUE TITLE
System.IO.IOException: There is not enough space on the disk. 

### ISSUE THREAD

**Issue by jkonecki** [Microsoft/Yams#35]
I have a Cloud Service of _medium_ with 2 instances running Yams host. There are 4 microservices deployed with sizes of 15MB, 16MB, 14MB and 14MB.

During upgrades I'm getting `Failed to perform update; Exception was: System.IO.IOException: There is not enough space on the disk. `

```
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) 
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) 
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access) 
at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.BeginDownloadToFile(String path, FileMode mode, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext, AsyncCallback callback, Object state) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlob.cs:line 405 
at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.BeginDownloadToFile(String path, FileMode mode, AsyncCallback callback, Object state) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlob.cs:line 386 
at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.TaskFromVoidApm[T1,T2](Func`5 beginMethod, Action`1 endMethod, T1 arg1, T2 arg2, CancellationToken cancellationToken) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 190 
at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.DownloadToFileAsync(String path, FileMode mode, CancellationToken cancellationToken) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlob.cs:line 511 
at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.DownloadToFileAsync(String path, FileMode mode) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlob.cs:line 498 
at Etg.Yams.Azure.Utils.BlobUtils.<DownloadBlobs>d__2.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at Etg.Yams.Azure.Storage.BlobStorageDeploymentRepository.<DownloadApplicationBinaries>d__8.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at Etg.Yams.Download.ApplicationDownloader.<DownloadApplication>d__3.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Etg.Yams.Update.ApplicationUpdateManager.<CheckForUpdates>d__6.MoveNext()
```

There is IMHO more than enough free space on all drives:
C: (Yams) - 481GB
D: (OS) - 20GB
E: - 780MB

When the error occurs the local folders for the latest versions of all 4 microservices contain only some of the files.

What could be the cause? How can I diagnose the issue further?

**Comment by remusrg** [comment]
Try increasing the LocalStorage sizeInMB in the .csdef of the service, the default I think is just 100MB.
https://msdn.microsoft.com/en-us/library/azure/gg557552.aspx#LocalStorage.
Let us know if that solves the problem.

**Comment by jkonecki** [comment]
Thank you, I'll try that.
I can see local folders for previous versions - does that mean that Local Storage should be increased to accomodate the size of all deployed versions instead of only one?

I've also noticed errors:
```
Failed to perform update; Exception was: System.IO.IOException: The process cannot access the file '<assembly-name>.pdb' because it is being used by another process.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Etg.Yams.Utils.FileUtils.<>c__DisplayClass2_0.<DeleteDirectoryIfAny>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Etg.Yams.Azure.Utils.BlobUtils.<DownloadBlobs>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Etg.Yams.Azure.Storage.BlobStorageDeploymentRepository.<DownloadApplicationBinaries>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Etg.Yams.Download.ApplicationDownloader.<DownloadApplication>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Etg.Yams.Update.ApplicationUpdateManager.<CheckForUpdates>d__6.MoveNext()
```

**Comment by remusrg** [comment]
Yes, LocalStorage should be sized to accommodate the combined size of all versions deployed. Eventually some of the old versions should be removed but that depends on your strategy (keep one/two versions back, or other). You can control that via DeploymentConfig.json. If you remove an app from config, local storage should get reclaimed automatically.

Not sure when the other exception might occur but it feels like something is still holding on to the file handle, perhaps a side effect to the other IOException related to space? Might want to restart the process/role as a workaround for now although you may not need to do that at all if you're going to increase the local storage and redeploy the cloud service.

**Comment by jkonecki** [comment]
I've redeployed with increased local storage and the update went fine. I'll be doing another one on Monday and if I don't experience the same problem I'll close the issue. 
Thank you very much for your help.

**Comment by jkonecki** [comment]
Closing the issue as increasing local storage limit solved the problem. 
Thank you @remusrg

**Comment by KUMARANTR** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at Xamarin.Android.Tools.Files.CopyIfChanged(String source, String destination)
   at Xamarin.Android.Tasks.MonoAndroidHelper.CopyAssemblyAndSymbols(String source, String destination)
   at Xamarin.Android.Tasks.LinkAssembliesNoShrink.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	App2.Android			





can anyone explain me why this happens ? please

**Comment by jkonecki** [comment]
You've run out of disk space.

Are you actually using Yams? Looks like you're running on Android...
