### ISSUE TITLE
Yams crashes with broken pipe

### ISSUE THREAD

**Issue by mhertis** [Microsoft/Yams#55]
When using health features of YAMS that involve the use of named pipes, killing an app cause the named pipe to break and cause the whole YAMS host to crash.

```
Topshelf v4.0.0.0, .NET Framework v4.0.30319.42000
The Yams service is now running, press Control+C to exit.
Topshelf.Hosts.ConsoleRunHost Critical: 0 : The service threw an unhandled exception, System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.Flush()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Etg.Yams.Process.Ipc.IpcConnection.Disconnect()
   at Etg.Yams.Process.Ipc.IpcConnection.Dispose()
   at Etg.Yams.Process.GracefulShutdownProcessDecorator.Dispose()
   at Etg.Yams.Process.AbstractProcessDecorator.Dispose()
   at Etg.Yams.Process.MonitorInitProcessDecorator.Dispose()
   at Etg.Yams.Process.SelfRestartingProcess.Dispose()
   at Etg.Yams.Application.ConfigurableApplication.Dispose()
   at Etg.Yams.Application.ApplicationPool.<RemoveApplication>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Etg.Yams.Application.ApplicationPool.OnApplicationExited(Object sender, ApplicationExitedArgs args)
   at Etg.Yams.Application.Application.OnProcessExited(Object sender, ProcessExitedArgs e)
   at Etg.Yams.Process.SelfRestartingProcess.OnFailed(String format, Object[] args)
   at Etg.Yams.Process.SelfRestartingProcess.<ExitedTryRestart>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
---> (Inner Exception #0) System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.Flush()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Etg.Yams.Process.Ipc.IpcConnection.Disconnect()
   at Etg.Yams.Process.Ipc.IpcConnection.Dispose()
   at Etg.Yams.Process.GracefulShutdownProcessDecorator.Dispose()
   at Etg.Yams.Process.AbstractProcessDecorator.Dispose()
   at Etg.Yams.Process.MonitorInitProcessDecorator.Dispose()
   at Etg.Yams.Process.SelfRestartingProcess.Dispose()
   at Etg.Yams.Application.ConfigurableApplication.Dispose()
   at Etg.Yams.Application.ApplicationPool.<RemoveApplication>d__7.MoveNext()<---

Stopping the Yams service
The Yams service has stopped.
```
https://stackoverflow.com/questions/45308306/gracefully-closing-a-named-pipe-and-disposing-of-streams

YAMS should handle this exception and only the app that has been killed should be affected, not the whole YAMS instance.

**Comment by nehmebilal** [comment]
Can you describe steps to reproduce please?

**Comment by mhertis** [comment]
Start Yams on local machine, use update WebApp sample, kill WebApp. :)
